"""initial

Revision ID: 317bf312f37e
Revises: 
Create Date: 2026-05-26 10:39:16.437218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '317bf312f37e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto', sa.String(), nullable=False),
    sa.Column('nome_cliente', sa.String(), nullable=False),
    sa.Column('valor_venda', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    # ### end Alembic commands ###
