"""Alterando o nome da tabela.

Revision ID: 7d94be01281a
Revises: 6a8230623e3f
Create Date: 2026-05-22 18:29:49.327081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d94be01281a'
down_revision = '6a8230623e3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto', sa.String(), nullable=False),
    sa.Column('cliente', sa.String(), nullable=False),
    sa.Column('valor_venda', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('produto', sa.VARCHAR(), nullable=False),
    sa.Column('cliente', sa.VARCHAR(), nullable=False),
    sa.Column('valor_venda', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('product')
    # ### end Alembic commands ###
